<a href="https://colab.research.google.com/github/anosharahim/capstone/blob/master/emotion_recognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Mounted at /gdrive
/gdrive


In [11]:
import pandas as pd
import os
import imageio
import numpy as np

In [4]:
#zipped_path = '/content/drive/MyDrive/Capstone/datasets/archive.zip'
#target_path = "/content/drive/MyDrive/Capstone/FER2013'
#unzip and extract files to gdrive
#!unzip zipped_path -d target_path

In [3]:
train_path = '/content/drive/MyDrive/Capstone/FER2013/train/'
test_path = '/content/drive/MyDrive/Capstone/FER2013/test/'

train_data = []
train_label = []
test_data = []
test_label = []

num_expressions = 6
labels = ['angry', 'Fear', 'Happy', 'Neutral', 'Sad', 'Surprise']


In [11]:
categories = os.listdir(train_path)


In [13]:
#keep track of y labels 
emotion_dictionary = {'angry':0, 'disgusted':1, 'fearful':2, 'happy':3, 'neutral':4, 'sad':5, 'surprised':6}

for emotion in os.listdir(train_path): 
  emotion_label = emotion_dictionary[emotion]
  folder_path = train_path + emotion + '/'
  for image in os.listdir(folder_path):
    image_file = folder_path + image 
    image_array = imageio.imread(image_file) #get image array from file 
    image_array = np.array(image_array) #convert to numpy array 
    #add image array and it's label to respective folders 
    train_data.append(image_array)
    train_label.append(emotion_label)

for emotion in os.listdir(test_path): 
  emotion_label = emotion_dictionary[emotion]
  folder_path = test_path + emotion + '/'
  for image in os.listdir(folder_path):
    image_file = folder_path + image 
    image_array = imageio.imread(image_file)
    image_array = np.array(image_array)
    test_data.append(image_array)
    test_label.append(emotion_label)

#convert x and y to numpy arrays 
train_data = np.array(train_data) 
test_data = np.array(test_data)
train_label = np.array(train_label) 
test_label = np.array(test_label)

[array([[ 68,  66,  67, ..., 254, 254, 254],
        [ 65,  64,  76, ..., 254, 254, 254],
        [ 60,  75,  85, ..., 254, 254, 254],
        ...,
        [191, 129, 106, ..., 253, 253, 253],
        [255, 246, 186, ..., 253, 253, 253],
        [250, 253, 255, ..., 253, 253, 253]], dtype=uint8),
 array([[ 86,  86,  92, ...,  94,  92,  85],
        [ 88,  89,  97, ...,  94,  93,  88],
        [ 89,  89,  95, ..., 101,  95,  93],
        ...,
        [155, 158, 153, ..., 128, 135, 140],
        [153, 154, 159, ..., 135, 141, 140],
        [152, 152, 152, ..., 141, 140, 139]], dtype=uint8),
 array([[109, 104, 100, ..., 143, 150, 149],
        [112, 107, 102, ..., 134, 137, 156],
        [110, 108, 103, ..., 154, 169, 179],
        ...,
        [ 77,  19,  31, ...,  96,  91,  86],
        [230,  83,  13, ...,  97,  90,  84],
        [242, 217,  49, ...,  94,  86,  85]], dtype=uint8),
 array([[ 25,  77,  86, ...,   0,   0,   0],
        [ 30,  87,  90, ...,   0,   0,   0],
        [ 37,  9